patches/0001-Add-GCC-8.2.patch
Pull in patch from upstream gcc that fixes use of typeof.
=> Update gcc-8.2 patch for arm_cmse.h c99 typeof fix

patches/newlib/2.5.0.20171222/0001-Print-sign-of-NaN-values-to-nano-vfprintf.patch
Pull in fix from upstream newlib for how NaNs are printed to match C
std.
=> newlib: Pull in fix for nan printf

.shippable.yml, meta-zephyr-sdk/recipes-hosttools/hosttools/hosttools-tarball.bb
This will publish the generated SDK to
https://builds.zephyrproject.org/zephyrproject-rtos/sdk-ng/<PR Number>/zephyr-sdk-<VERSION>-setup.run
Version is what we have in the VERSION file in the repo.
Fixed #39
=> ci: publish generated SDK for testing

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb
The zephyr-20190226 branch adds a few patches for fixing the Zephyr RTOS
awareness, and a set of workaround patches for reset issue on CC3220.
=> openocd: bump to zephyr-20190226 branch

configs/arc.config, configs/arm.config, configs/i586.config, configs/iamcu.config, configs/mips.config, configs/nios2.config, configs/riscv32.config, configs/xtensa.config
The --enable-initfini-array configure flag forces GCC to use
init/fini arrays instead of just init/fini functions, as GCC
would choose to do functions depending on arch. With only
init/fini functions, apps built with coverage would not
dump any coverage data because __gcov_init() is never called.
With this flag, GCC will use init array which is required
for the correct operation of gcov_static_init().
=> configs/all: add --enable-initfini-array to gcc configure

meta-zephyr-sdk/recipes-hosttools/bossa/bossa_git.bb
This reverts commit 005cdc7c565289b9760ca95f9d597264348d48b5.
Revert back to 1.7 bossa as that version works, the appears to be a
known issue with newer version not flashing:
https://github.com/shumatech/BOSSA/issues/96
Fixes: #59
=> Revert "Update bossa to 1.9.1"

scripts/make_zephyr_sdk.sh
The script to create the SDK file looks for built toolchain
archive name containing "mips32r2", but the actual archive
is mips.tar.bz2. So update the script to look for the correct
name.
=> Fix MIPS toolchain not being included in SDK

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb
We pull in some of the ARC fixes from openocd (GDB fix still pending
upstream).  Also pull in a cleaner fix for the TI CC32xx reset issue.
=> openocd: Update rev for TI & and some ARC fixes

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-qemu-nios2-Add-Altera-MAX-10-board-support-for-Zephy.patch, meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
Updated nios2 patch to build with qemu 4.0.0
=> qemu: bump to 4.0.0 release

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb
We need the workaround for the nSRST for TI CC13x2/CC26x2 platforms.
=> openocd: Pull in newer version for XDS110 reset issue

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
In order to support Cortex-R development, we will run a xlnx-zcu102 qemu
machine.  However, the application processors on that machine are 64 bit
A53s so the qemu executable to run it is aarch64-softmmu.
Signed-off-by: Bradley Bolen <bbolen@lexmark.com>
Note that this will allow running the "Hello World" sample application.  However, none of the other samples will run because the GIC is not hooked up to the R5 on the zcu102.  If that is not sufficient, then I'm fine dropping this PR and we can come up with some other platform for cortex-r support.
=> qemu: Enable aarch64 target

patches/gcc/8.3.0/0043-RISC-V-update-t-elf-multilib-by-hand-for-64-bit-mcmo.patch
Pull in patch to gcc that builds 'mcmodel=medany' multilibs on the
64-bit targets.
=> Update multilib for medany on 64-bit targets

patches/newlib/git-b06f1b57/xtensa-enable-remainderf.patch, patches/newlib/git-b06f1b57/xtensa-enable-sqrtf.patch
Upstream GCC does not provide these functions in libgcc,
so need to enable them in newlib/libm.
=> xtensa: enable remainderf and sqrtf in newlib

scripts/make_zephyr_sdk.sh
Change from /opt/zephyr-sdk to ~/zephyr-sdk as the default so you
dont need root priv.
=> make home the default install dir

scripts/make_zephyr_sdk.sh
Since we now have xtensa target specific toolchains the generic xtensa
target doesn't exist.  So remove it.  (causes a build error).
Also remove mips (its been commented out).
=> make_zephyr_sdk.sh: remove parse_toolchain_name call for xtensa

configs/x86_64-zephyr-elf.config, patches/gcc/9.2.0/0012-Add-support-to-build-for-x86_64-zephyr-elf.patch, patches/newlib/3.1.0.20181231/0002-Recognize-x86_64-zephyr.patch, patches/newlib/3.1.0.20181231/0003-Support-building-for-32-bit-under-x86_64.patch
* Ran autoreconf on library projects to support the x86_64-zephyr-elf tuple.
* Remove the check for multilib in configure as we are now hard-coding the MULTILIB_OPTIONS in t-zephyr64. The previos attempt was using the Linux version of t-linux64. That is targeting shared library placement for live system. Since Zephyr only needs the static libraries for linking purpose only, there is no need to put them under /lib or /lib64. So simplify it a bit.
* Set m64 as the default for multilib so it won't build 64-bit libraries twice (one under /lib, and one under /lib/64).
* Add LINK_SPEC to specify default binary format for final linking. This helps with compiler flag check with cmake as it does not know what format to use, and the default elf_x86_64 was being used to link both 32 and x32 targets. …
=> x86_64: update GCC 9.2.0 patch file and default march

go.sh
As the missing dependency was fixed, there is no need to call
build three times to build the tools.
=> tools: call build once

.shippable.yml, patches/gcc/9.2.0/0012-Add-support-to-build-for-x86_64-zephyr-elf.patch, patches/newlib/3.1.0.20181231/0003-Support-building-for-32-bit-under-x86_64.patch, scripts/make_zephyr_sdk.sh
This adds -msoft-float to the x86_64 multilib options for 32-bit targets, so that it has the same libraries as i586-zephyr-elf. It is now possible to use one toolchain to build for all x86 targets.
Note that x32 is removed as x86_64 arch is built as true 64-bit target on current Zephyr master. Also removes the tm_file and md_unwind_header lines which came from x86_64-*-linux and are not Zephyr related.
Requires https://github.com/zephyrproject-rtos/zephyr/pull/20178
=> x86_64: update patch files to allow building for i586 targets

meta-zephyr-sdk/conf/distro/include/zephyr-sdk.inc, meta-zephyr-sdk/patches/modern-host-01-use-automake-1.15.1.patch, meta-zephyr-sdk/patches/modern-host-02-fix-cross-localedef-native-2.24-locale-t-h.patch, meta-zephyr-sdk/patches/modern-host-03-morty-elfutils-fix-fallthrough-warnings-and-printf-overflow.patch, meta-zephyr-sdk/patches/modern-host-04-fix-e2fsprogs-1.43-create-inode-type-conflict.patch, meta-zephyr-sdk/patches/modern-host-05-fix-gcc-6.2-ubsan-isoc-incompliance.patch
This PR adds the patches required for building meta-zephyr-sdk on Ubuntu 18.04 host.
This closes #129.
=> Support Ubuntu 18.04 host for building meta-zephyr-sdk

meta-zephyr-sdk/recipes-devtools/xilinx_qemu/xilinx-qemu_git.bb, meta-zephyr-sdk/recipes-hosttools/hosttools/hosttools-tarball.bb
This commit adds Xilinx QEMU recipe for building AArch64 QEMU
(qemu-system-xilinx-aarch64).
The Xilinx QEMU fork is necessary because the arm-generic-fdt machine
type, required to properly emulate the Xilinx Zynq SoC, is only
availabe on it at this time.
For more details, refer to the issue #132.
=> Add Xilinx QEMU (qemu-system-xilinx-aarch64)

scripts/make_zephyr_sdk.sh
We hit an error case when we added arm64, fix the handling of how we
determine the toolchain file name.  First guess that it is $arch.tar.bz2
and if not fall back to the old style check (which will get used for the
host tools).
=> scripts/make_zephyr_sdk: fix for arm v arm64

scripts/template_dir
Since we now install the xtensa toolchains under xtensa/ we need the
umask to be 0022 if EUID == 0.  Otherwise we can't access the xtensa
install dir.
=> scripts: change umask if we are installing as root to fix dir perms

patches/gdb/8.3.1/0001-gdb-remote-make-tid-pid-type-long-in-wite_ptid.patch
For ARC in Zephyr RTOS TID's values start from 0x80000000.
Passing such big values to write_ptid function cause
overflow of "int tid" variable. As a result TID becomes
negative and trying to switch to such thread leads to such message:
(gdb) thread xxx
Thread ID xxx has terminated.
Adding this GDB patch fixes thread-aware debugging for Zephyr on ARC boards
Patch in patchwork:
http://patchwork.sourceware.org/patch/35764/
Signed-off-by: Evgeniy Didin <didin@synopsys.com>
=> gdb/remote: Fix write_ptid tid/pid overflow

meta-zephyr-sdk/patches/gcc-9-0001-Fix-elfutils-for-GCC-9.patch, meta-zephyr-sdk/patches/gcc-9-0002-Fix-glib-2.0-for-GCC-9.patch
This commit adds a set of patches to allow building the 'tools' with
GCC 9.
=> Add patches for building 'tools' with GCC 9

meta-zephyr-sdk/recipes-devtools/xilinx_qemu/files/0001-Revert-target-arm-Revert-back-to-YIELD-for-WFI.patch, meta-zephyr-sdk/recipes-devtools/xilinx_qemu/xilinx-qemu_git.bb
```
The Xilinx QEMU deliberately breaks the WFI (wake up from interrupt)
instruction, possibly for performance and cosimulation stability
reasons, and this causes the Zephyr CI tests, that expect the WFI
instruction to function properly, to fail.
This commit adds a patch to revert the offending Xilinx QEMU commit
since accurate simulation behaviour takes precedence over performance
for CI testing, and the Zephyr will not use the cosimulation feature.
```
This PR includes a commit from the PR #163 (closes #163 if merged before).
=> xilinx_qemu: Fix WFI instruction

configs/arm64.config
This commit enables the "arm-zephyr-eabi" target support in the AArch64
gdb in order to support the devices that integrate both ARMv7 and ARMv8
cores into single system-on-chip (e.g. Xilinx Zynq UltraScale+ and TI
AM65x devices).
Related discussion at https://github.com/zephyrproject-rtos/zephyr/issues/20217#issuecomment-565871161.
=> arm64: Enable arm-zephyr-eabi multi-arch support for gdb

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb
* pull in missed changes on older branch (arc & Zephyr RTOS awareness
fix)
* Pull in some fixes from upstream tree.
=> openocd: update to pull in fixes

patches/newlib/3.1.0.20181231/0003-Support-building-for-32-bit-under-x86_64.patch
The 32-bit build of newlib didn't include setjmp/longjmp due to us not
configuring it correctly.  In configure.host we needed to set
mach_add_setjmp=true for 'm32'.  Also mimic i.86 in setting
libm_machine_dir=i386.
Fixes #179
=> newlib: Fix 32-bit build of newlib for setjmp

meta-zephyr-sdk/recipes-devtools/xilinx_qemu/files/0001-Revert-target-arm-Revert-back-to-YIELD-for-WFI.patch, meta-zephyr-sdk/recipes-devtools/xilinx_qemu/files/0002-Enable-WFI-CPU-halting-in-icount-mode.patch, meta-zephyr-sdk/recipes-devtools/xilinx_qemu/xilinx-qemu_git.bb
The Xilinx QEMU deliberately breaks the WFI (wake up from interrupt)
instruction when icount mode is used, possibly for performance and
cosimulation stability reasons, and this causes the Zephyr CI tests,
that expect the WFI instruction to function properly, to fail.
This commit adds a patch to enable the CPU halt behaviour of the WFI
instruction in the icount mode, since accurate simulation behaviour
takes precedence over performance for CI testing, and the Zephyr will
not use the cosimulation feature.
This PR addresses the issue identified in https://github.com/zephyrproject-rtos/zephyr/pull/22904#issuecomment-591209160.
=> xilinx_qemu: Fix WFI instruction for icount mode

meta-zephyr-sdk/recipes-devtools/qemu/files/0004-hw-sparc-leon-Switch-to-transaction-based-ptimer-API.patch
Fixes following bug:
`sdk-zephyr-qemu/git-r0/git/hw/core/ptimer.c:384: ptimer_transaction_commit: Assertion `s->in_transaction' failed.`
I'm not sure if it's okay to just edit existing patch, or to add another, but editing existing patch for now.
=> SPARC: fix issue with timer in QEMU machine AT697

meta-zephyr-sdk/recipes-devtools/qemu/files/0005-riscv-sifive_e-Support-changing-CPU-type.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0006-target-riscv-Add-a-sifive-e34-cpu-type.patch, meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
This change allows the sifive_e machine to run with different CPU
targets to enable different ISA entensions. To that end it also
introduces a new sifive-e34 CPU type which provides the same ISA
as sifive-e31, with the addition of the single precision
floating-point extension (f). The default CPU for the sifive_e
machine is unchanged.
Signed-off-by: Corey Wharton <coreyw7@fb.com>
=> qemu: Add support for changing CPU type in sifive_e machine.

scripts/template_dir
Needed for unattended setups that do not want to answer yes (with -y) to
the prompt about creating ~/.zephyrrc.
See Arch Linux package zephyr-sdk in AUR: 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zephyr-sdk#n110
=> scripts: template_dir: setup: add -[no]rc arg

patches/gcc/9.2.0/0001-arm-Fix-use-of-CRC32-intrinsics-with-Armv8-a-and-har.patch
Backport patch from gcc to fix issue with building w/arm_acle.h.
=> Fix use of CRC32 intrinsics with Armv8-a and hard-float

scripts/template_dir
This commit reduces number of recommended folders when user is
installing outside any of the default paths.
For example, is user uses a path under /usr/ but not a default search
path, such as /usr/mysdk, then only the /usr/ based recommended paths
are printed.
Also a link to Zephyr docs for all search paths are given.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
=> template_dir: improved help text for toolchain install dir

patches/newlib/3.1.0.20181231/0004-newlib-configure.host-Add-host-config-for-zephyr.patch
Add a zephyr case to newlib/configure.host so we get the same config on
all arch's.  Fix the fact that some arch's like x86 were getting
-DMISSING_SYSCALL_NAMES set in newlib which we don't want.
Fixes: #221
=> newlib: Make configure host consistent for all arch's

.buildkite/deploy.yml, .buildkite/hooks/pre-command, .buildkite/pipeline.yml
Add buildkite related CI files.  We add the starts of a deploy.yml that
will not directly get invoked by buildkite for security reasons.
=> ci: Add initial buildkite support

patches/newlib/3.1.0.20181231/0003-Support-building-for-32-bit-under-x86_64.patch
The 32-bit build on Zephyr main tree is targeting Pentium-based
devices. However, given the target tuple, newlib is being built
targeting i686 by default. This emits instructions that cannot
run on Pentium-based devices. So add a march=pentium when
newlib is being built for x86_64 32-bit.
=> x86_64: newlib: use march=pentium for 32-bit

scripts/make_zephyr_sdk.sh
The arch specific toolchains are missing the cmake bits, which means if
you install one of them it will not work with zephyr.
=> make_zephyr_sdk: Add cmake bits to arch specific toolchains

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-hw-sparc-Add-leon-at697-machine.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0001-qemu-nios2-Add-Altera-MAX-10-board-support-for-Zephy.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0002-hw-sparc-leon-Fix-compilation-errors.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0003-hw-sparc-leon-timer-Call-leon_timer_io_read-for-TIME.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0004-hw-sparc-leon-Switch-to-transaction-based-ptimer-API.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0006-Add-support-for-ARCv2-architecture.patch, meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
=> qemu: Bump to v5.0.0

meta-zephyr-sdk/recipes-devtools/qemu/files/0007-ARC-Fix-icount-support.patch, meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
This adds `icount` support for ARC needed for https://github.com/zephyrproject-rtos/zephyr/pull/26646.
=> qemu: Add icount for ARC

meta-zephyr-sdk/recipes-devtools/qemu/files/0008-os_find_datadir-search-as-in-version-4.2.patch, meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
If we move the install of qemu from how --prefix is set we run into
issues trying to find bios files.  This is because searching in
share/qemu relative to the executable was removed in qemu 5.0.0.  Pull
in a patch from the qemu-devel mail list that restores searching in
share/qemu.
Fixes #242
=> qemu: Fix search path breakage in qemu 5.0.0.

scripts/make_zephyr_sdk.sh
Rename toolchain packages to include ${machine} and linux in the name to
handle both support for x86-64 & aarch64 (arm64) linux builds as well as
in the future possibly having Win and MacOS X builds.
=> make_zephyr_sdk: Rename toolchain packages to include arch & OS

cmake/zephyr/host-tools.cmake
To support both x86_64 and aarch64 host env we need to set
HOST_TOOLS_HOME correct and we utilize OS_PLATFORM from
cmake_host_system_information to do that (which on linux will be the
result of `uname -m`).
=> cmake: Set HOST_TOOLS_HOME based on OS_PLATFORM

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb
Bump SHA to point to openocd based on upstream SHA:
fa9a4d4db5cfe44b7aadb1b8ef220f94423742a1
=> openocd: bump to new upstream based openocd

patches/gcc/10.2.0/0014-RISC-V-update-t-elf-multilib-by-hand-for-64-bit-mcmo.patch
We dropped a patch when updating to gcc-10.2 that handled additional
multilib variants we want for riscv-64.
=> gcc: Add missing multilib on riscv-64

go.sh
Pull in fix for compat on centOS.  See commit in upstream crosstool-ng:
commit 57f59092852dff18fbda68fdbf23f850ad182c40
Author: Alexey Brodkin <abrodkin@synopsys.com>
Date:   Wed Oct 14 22:35:03 2020 +0300
binutils: Disable glob for better portability
Fixes: #280
=> crosstool-ng: Update to newer upstream for centos build fix

scripts/template_dir
Fixes a few issues encountered when scripting the installation for distro package:
1. Issue introduced when cmake module was added: the user was prompted even if -y was passed, which broke unattended installation.
2. CMake module installed under $HOME unconditionally, and the path to SDK in the cmake module equals destination directory, which is not necessarily the same as the final installation path in the system (details below). This issue is not solved, but only worked around by adding -[no]cmake args so that the problematic cmake module generation can be disabled and performed out-of-band by the packager script. 
3. Order of -y and -[no]rc  arguments mattered due to -y unintentionally overriding -[no]rc. Overlooked in 6dd3e26c271bbf139f6d30523bc55fc7673b52f5.
4. Duplication of code …
=> scripts/template_dir (setup.sh): fixes for unattended setup for distro packagers

cmake/zephyr/target.cmake
Define sparc-zephyr-elf as tool prefix when ARCH=sparc. This allows
cmake to generate the SDK-NG SPARC toolchain path.
=> cmake: Add SPARC support

patches/gcc/10.2.0/0015-Add-LEON-multilibs-for-sparc-zephyr-elf.patch
Successfully tested with Zephyr sanitycheck on the SPARC board configurations `qemu_leon3`, `gr716a_mini` and `generic_leon3`.
A summary of the differences between `-mcpu` options are given below.
| Option                              | mul/div | casa |
| ----------------------------- |  --- | --- |
| -mcpu=v7 (or no -mcpu=) |        NO     |  NO |
| -mcpu=leon                      | YES   |   NO |
| -mcpu=leon3                    | YES   |   YES |
| -mcpu=leon3v7                 |  NO  |     YES |
`mul/div` means that the compiler will generate multiplication and
division instructions, which is a SPARC V8 feature. There are some
use cases for compiling without `mul/div`:
- If the hardware is synthesized without `mul/div` instructions.
- To reduce interrupt response time on systems with …
=> gcc: update multilibs for SPARC

patches/gcc/10.2.0/0016-gcc-libgcc-t-arm-Fix-mcmse-compile-test-for-setting-.patch
There is a bug in how libgcc detects if the compiler suppoerts -mcmse.
Fix the t-arm makefile stub to correctly report if -mcmse is supported
Fixes #301
=> gcc: Fix building of libgcc on w/regards to -mcmse

go.sh
When we build on MacOS since we create a sparseimage file to do
builds the location of the sdk patches isn't correct.  Fix this
by copying the patches/ dir into the mounted sparseimage file.
=> Fix up patches for MacOS builds

patches/gcc/10.2.0/0017-x86_64-zephyr-elf-fix-soft-float-for-x86-32-bit.patch
This fixes soft-float build for x86 32-bit (-m32 -msoft-float)
under x86_64-zephyr-elf multilib build. This now actually
includes the soft float functions.
=> x86_64: fix soft float for x86 32-bit

cmake/zephyr/Kconfig
During release of the Zephyr SDK 0.12, the corresponding Kconfig setting
was missed.
This commit changes `TOOLCHAIN_ZEPHYR_0_11` to `TOOLCHAIN_ZEPHYR_0_12`
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
=> cmake: updating TOOLCHAIN_ZEPHYR_0_11 --> TOOLCHAIN_ZEPHYR_0_12

cmake/zephyr/target.cmake
There is an ongoing effort in Zephyr to separate the ARM architecturefrom ARM64 (AArch64). As part of this work, a new architecture will be introduced called 'arm64'.
To be able to keep using the same SDK to compile old and new Zephyr releases, we need to add a new cross-compile target specifically for 'arm64' together with the legacy 'arm' target.
@galak @tejlmand  this should be a pretty harmless change to be able to support the current situation and at the same time the new changes that I'm going to submit soon, where the ARM64 will be separated from the ARM architecture.
=> cmake: Add arm64 cross-compile target

go.sh, release-notes.md
Update build script to pull in the crosstool-ng commit that supports
the new `CT_CC_GCC_TM_CLONE_REGISTRY` config option.
This option is disabled by default and will therefore add
`--disable-tm-clone-registry` during gcc build to disable the unused
transactional memory clone registry in libgcc.
For more details, refer to the issue #345.
Fixes #345.
=> crosstool-ng: Update to pull in gcc TM clone registry config

release-notes.md
Update build script to pull in the crosstool-ng commit that corrects
the build specs for the libstdc++ nano, which is used with newlib-nano.
For more details, refer to the issue #346.
Fixes #346
=> crosstool-ng: Update to pull in libstdc++ nano config fix

.github/workflows/mac.yml
Add a github workflow that will build macosx-x86_64 toolchains and
publish the packages on release.  The workflow only runs after a
commit since it takes 6+ hours to run on current github macosx
builders.
A few notes / caveats on the macosx toolchain build / packages:
* NO host tools (ie qemu, openocd, dtc, etc).  Since we dont build
yocto on MacOS we dont currently have any of the host tools at
this time
* GDB build is without python.  The python GDB on MacOS doesn't
currently work so we limit GDB to only a non-python enabled
build.
* gcc build with --without-zstd to make builds portable.  As zstd
isn't a common library on MacOS we build with this flag since
it is found in homebrew with the github MacOS setup
=> ci: Add workflow to build macosx-x86_64 toolchains

scripts/template_dir
The current MacOS builds do not have environment-setup* files
or version-* that come from the Yocto hosttools builds.  So add
some checks in template_dir to see if those files exist before
trying to remove or move them.
=> scripts/template_dir: Add file exist checks

.buildkite/deploy.yml
Filenames should be OS.MACHINE, not the otherway around.  Also had
an extra . in the cmake filename.
=> ci: deploy fix filenames

.github/workflows/mac.yml
Update the github mac action to match how go.sh and the other
scripts now work.
=> ci: Fixup github mac action based on latest ci changes

go.sh
pull in nano.spec fix that links with -lc_nano instead of -lc (same
for other nano lib variants, libm, libstdc++, etc..)
Fixes #369
=> crosstool-ng: Update to pull in fix for nano.spec

meta-zephyr-sdk/recipes-devtools/qemu/files/0018-arc-virt-Make-target-memory-size-configurable.patch, meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
We used to be very generous with memory allocation for ARC's "virt" board assuming people would run Linux on it and all 2 GiB of RAM will be consumed anyway.
But in case of Zephyr we don't need that much, yet QEMU tries to allocate 2 GiB right away meaninglessly claiming hosts's memory.
And while it's typically not a big deal if 1 QEMU instance is run on an up-to-date host (we have 10s of GiBs to our disposal), in case of massive parallel QEMU execution like in Zephyr's "twister", it really starts to get in a way. So we now allow user to specify amount of memory we'd like to have on emulated target and thus significantly lower memory pressure and requirements on "twister"-running hosts.
Fixes https://github.com/zephyrproject-rtos/sdk-ng/issues/291.
=> qemu: Allow setup of ARC's "virt" board memory size

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb, release-notes.md
Pull in the following OpenOCD fixes:
* tfc/target: stm32: Fix missing DBG clock on stm32g0/l0
* target/arc: implement dummy checksum_memory()
=> openocd: Pull in OpenOCD fixes

configs/mips.config, release-notes.md
This change turns off the use of the GP register for small data values on MIPS.
This allows a few more testcases to pass.
Signed-off-by: Remy Luisant <remy@luisant.ca>
=> config: Disable the GP register optimizations on MIPS

go.sh
The old ISL mirror server has permanently gone down, so switch to a new
mirror.
This fixes the CI failures due to the ISL library mirror being
unavailable.
Zephyr crosstool-ng PR: https://github.com/zephyrproject-rtos/crosstool-ng/pull/13
=> crosstool-ng: Update to pull in ISL mirror fix

README.md
This commit removes obsolete information from the README file and adds
information related to the new multi-platform Zephyr SDK as well as the
new CI infrastructure.
=> README: Update for new multi-platform Zephyr SDK

.github/workflows/ci.yml, .github/workflows/release.yml
This commit adds a new job to the CI workflow that is not a part of a
matrix and depends on the distribution bundle test matrix jobs, such
that it only runs when the distribution bundle test jobs do not fail
(i.e. all distribution bundle tests pass).
The purpose of this is to provide a checkpoint which the GitHub branch
protection rule can use to enforce the required checks for merging pull
requests, because GitHub does not support specifying a job that is part
of a matrix for this purpose.
Remove this when GitHub is updated to support specifying the steps that
are part of matrix jobs for the required checks.
Tested in https://github.com/zephyrproject-rtos/sdk-ng-testing/pull/3.
NOTE: "Test Result" job should be added to the required …
=> ci: Add matrix-less checkpoint for test result

scripts/template_setup_posix
When invoking the host tools setup SFX, the POSIX setup script
incorrectly assumed that the host architecture for Linux is always
x86-64.
This commit updates the setup script to invoke the host tools setup SFX
of the host architecture that is running the script.
Fixes #438
=> scripts: Fix incorrect Linux host tools setup invocation

.github/workflows/ci.yml
This commit updates the CI workflow to enable the 'dotglob' shell
option while cleaning up the working directories so that all contents
of the working directories, including the hidden files and directories
starting with a dot, are removed.
Note that removing the working directory and re-creating it is not an
option because that is known to break the GitHub Actions runner on the
macOS.
=> ci: Enable dotglob shell option for working directory clean-up

.github/workflows/ci.yml
This commit updates the CI workflow to pull the Docker images from the
GitHub Container Registry (GHCR) to work around the pull rate limits of
the DockerHub.
=> ci: Pull Docker images from GitHub Container Registry

.github/workflows/ci.yml
This commit updates the CI workflow to cache the crosstool-ng and poky
source files used for building the Zephyr SDK in the AWS S3, in order
to speed up the builds as well as to improve the availability of the
source files.
Closes #399
=> ci: Cache source files

.github/workflows/ci.yml, .github/workflows/release.yml
This commit updates the release workflow to explicitly pass the secrets
to the reusable CI workflow (invoked via `workflow_call`) because the
repository secrets are not available by default in the reusable
workflows.
=> ci: release: Pass secrets to reusable workflows

.github/workflows/ci.yml
The commit 2fc95f5c1a04f5d606ed4aaa4af6b877b71f99fe modified the CI
workflow to use the `pull_request_target` trigger for the pull request
runs.
The `pull_request_target` action runs in the context of the target
branch and the GitHub `checkout` action will check out the target
branch commit by default, thereby not building the actual changes in
the pull request branch.
This commit updates the `checkout` action to check out the pull request
head commit when running in the context of `pull_request_target`.
=> ci: Fix pull request checkout

meta-zephyr-sdk/recipes-devtools/arc_qemu/arc-qemu_git.bb
This commit updates the ARC QEMU to 2022.04.26 release (tag).
NOTE: This change was initiated because the original commit
2625a6fbc3f60233e1d340931d00242d82230091 no longer exists in the
upstream repository.
=> meta-zephyr-sdk: arc_qemu: Update to 2022.04.26 release

.github/workflows/ci.yml
This commit updates the crosstool-ng submodule to track the Zephyr
branch based on the crosstool-ng 1.25.0 release
(`zephyr-crosstool-ng-1.25.0`).
Closes #471
=> crosstool-ng: Pull in crosstool-ng 1.25.0 branch

.github/workflows/ci.yml
This commit updates the CI workflow to invoke the twister with the
`--force-color` option so that the test logs are displayed in color
in the GitHub Actions web console.
=> ci: Force twister color output

.github/workflows/ci.yml
This commit updates the CI workflow to use the Zephyr `topic-sdk15`
branch, which contains the Zephyr-side patches required for the
upcoming Zephyr SDK 0.15.0 release, for testing.
Revert this patch when the Zephyr SDK 0.15.0 is release and all the
tasks documented in zephyrproject-rtos/zephyr#46491 are completed.
=> ci: Use Zephyr topic-sdk15 branch for testing

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
This commit pulls in the Zephyr OpenOCD branch that is based on the
latest OpenOCD commit as of 2022-06-11 (`zephyr-20220611` branch).
=> openocd: Pull in zephyr-20220611

.github/workflows/ci.yml
This commit updates the CI workflow to use the Zephyr `topic-sdk15`
branch, which contains the Zephyr-side patches required for the
upcoming Zephyr SDK 0.15.0 release, for testing.
Revert this patch when the Zephyr SDK 0.15.0 is release and all the
tasks documented in zephyrproject-rtos/zephyr#46491 are completed.
=> ci: Use Zephyr topic-sdk15 branch for testing [v2]

scripts/template_setup_posix, scripts/template_setup_win
This commit disables the following ARC targets because the patches for
the latest GNU toolchain components are not currently available:
* arc-zephyr-elf
* arc64-zephyr-elf
Revert this after all toolchain components are updated to include the
ARC patches.
=> scripts: template: Disable ARC targets

.github/workflows/ci.yml
This commit adds an option to start debug session from a runner when
manually starting the CI workflow through the `workflow_dispatch`
event or in a pull request by setting a debug label.
=> ci: Add option to start debug session

.github/workflows/ci.yml
This commit increases the macOS workspace volume size to 70GB because
the current size of 50GB is insufficient and causes "no space left"
error during AArch64 macOS host toolchain builds.
=> ci: Increase macOS workspace volume size

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
This commit updates the QEMU version to 7.0.0.
QEMU 7.0 is required to support the new ratified RISC-V extensions such
as Zve* and Zb*.
Closes #480
=> qemu: Update to QEMU 7.0 release

.github/workflows/ci.yml
This commit adds the `qemu_riscv32e` to the test platform list for the
`riscv64-zephyr-elf` toolchain so that all supported base RISC-V
architecture variants are tested.
=> ci: Add RISC-V rv32e test platform

.github/workflows/ci.yml
The `intel_s1000_crb` platform support, which is currently used for
testing the Intel S1000 Xtensa toolchain, has been removed from the
upstream Zephyr.
This commit updates the CI workflow to test the Intel S1000 Xtensa
toolchain using the `intel_adsp_cavs18` platform, which is another
board that builds using this toolchain.
=> ci: Replace intel_s1000_crb with intel_adsp_cavs18

meta-zephyr-sdk/recipes-devtools/arc_qemu/arc-qemu_git.bb
This commit updates the ARC QEMU to 2022.08.04 tag.
Closes #481
=> meta-zephyr-sdk: arc_qemu: Update to 2022.08.04 release

cmake/zephyr/target.cmake
Both 32bit and 64bit ARCv3 have same toolchain prefix - `arc64-zephyr-elf`
=> ARC: ARCv3: fix toolchain prefix for ARCv3 32bit

.github/workflows/ci.yml
The owner UID of the GITHUB_WORKSPACE directory may not match the
container user UID because of the way GitHub Actions runner is
implemented, and this can cause the Git operations to fail unless the
workspace directory is explicitly listed as a "safe directory."
For more details, refer to the following GitHub issue:
actions/checkout#760
Remove this workaround when GitHub comes up with a fundamental fix for
this problem.
=> ci: Add container owner mismatch workaround

.github/workflows/ci.yml
This commit adds the GitHub runner temporary directory (`RUNNER_TEMP`)
to the Git safe directory list because the `meta-zephyr-sdk` build
process may check out source files under this directory.
=> ci: Add runner temp directory to git safe directory list

.github/workflows/ci.yml
Since Git 2.35.1, the `safe.directory` config can be set to a wildcard,
which has the effect of disabling the ownership check.
=> ci: Disable Git directory ownership check

.github/workflows/ci.yml
This reverts commit https://github.com/zephyrproject-rtos/sdk-ng/commit/589923639e51d566a333fd028c22fe67d1cdc4ea and https://github.com/zephyrproject-rtos/sdk-ng/commit/cd04a0ba13b90f891557e68b64a45b3c78f2f9aa.
=> Revert "ci: Use Zephyr topic-sdk15 branch for testing"

README.md
Adds a note on a typical workflow to generate the Zephyr SDK to test
changes to gcc or other submodules.
Signed-off-by: Kevin Townsend <kevin.townsend@linaro.org>
=> doc: readme: Add note on patch testing workflow

cmake/zephyr/Kconfig
This commit updates the Kconfig symbol name to reflect the current version of Zephyr SDK (the 0.15.0 release forgot to do it).
=> cmake: Update Kconfig symbol name for 0.15

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
This commit pulls in the fix for the OpenOCD failing to flash a target when the target is in sleep state.
Note that this is only a workaround until the Zephyr-side OpenOCD configurations are updated to fundamentally fix this issue -- refer to the linked OpenOCD commit message for more details.
OpenOCD PR: https://github.com/zephyrproject-rtos/openocd/pull/52
=> openocd: Pull in sleeping target flash failure fix

.github/workflows/ci.yml
This commit updates the CI workflow to use a larger 8-core runner for
testing Zephyr SDK distribution bundle on Windows.
=> ci: Use larger runner for Windows testing

.github/workflows/ci.yml, scripts/template_setup_posix, scripts/template_setup_win
This commit updates the CI workflow to output a toolchain list file (`sdk_toolchains`) while building a distribution bundle and updates the distribution bundle setup scripts to use it instead of a hard-coded one.
This allows partial distribution bundle builds without all the supported toolchains to be properly handled by the distribution bundle setup script.
Closes https://github.com/zephyrproject-rtos/sdk-ng/issues/516
=> scripts: Use toolchain list from distribution bundle build

.github/workflows/ci.yml
This commit updates the CI workflow to shorten the distribution bundle path on Windows for testing because the full path can be too long for some architectures and may cause build failures.
=> ci: Shorten distribution bundle path on Windows for testing

scripts/template_setup_win
`!` must be used instead of `%` inside a loop when referencing a variable that is changed within the loop.
=> scripts: template_setup_win: Fix toolchain list loading

.github/workflows/ci.yml
This commit updates the CI workflow to allow running the workflow in the branches prefixed with `topic-` (i.e. topic branches).
=> ci: Allow running CI workflow in topic branches

.github/workflows/ci.yml, scripts/template_setup_posix, scripts/template_setup_win
This series updates the CI workflow to output `.tar.xz` (Linux and macOS) and `.7z` (Windows) build artifacts to reduce the overall artifact sizes.
Closes #567
=> ci: Use LZMA compression for build artifacts

scripts/template_setup_posix
This commit updates the POSIX setup script to use `linux*` instead of `linux-gnu*` to detect the Linux host OS type because some distros may omit the `-gnu` part.
=> scripts: template_setup_posix: Fix Linux OS type detection

meta-zephyr-sdk/scripts/meta-zephyr-sdk-clone.sh
This commit pulls in the Poky commit that downgrades the glibc version to 2.27 in order to ensure that the nativesdk binaries are compatible with older Linux distros.
---
Poky commit https://github.com/zephyrproject-rtos/poky/commit/18a79ded82711695fc91711029529d7161a13610
Fixes #584
=> meta-zephyr-sdk: Downgrade glibc to 2.27

scripts/template_setup_posix
The Linux host tools for Zephyr SDK are packaged using the Yocto nativesdk recipe and its installer may print out the messages that can be potentially misleading to the Zephyr SDK users, who do not need to understand the internals of the Zephyr SDK host tools integration.
This commit updates the setup script to suppress any console outputs from the Yocto nativesdk installer script.
=> template_setup_posix: Suppress Yocto nativesdk installer messages

scripts/template_setup_posix
The commit 05f60473445299a9650048e876d8f84838b19359 moved the toolchain list from the setup script itself to an external file (`sdk_toolchains`).
This change also introduced a delimiter change from 'SPACE' to 'LF' that broke the regular expression used by the toolchain (`-t`) flag handler, which assumes the 'SPACE' delimiter.
This commit reworks the setup script to convert the 'LF' delimiter to 'SPACE' after loading the toolchain list from `sdk_toolchains` to fix this issue.
=> template_setup_posix: Fix command line toolchain flag handling

.github/workflows/ci.yml, .github/workflows/release.yml
This series includes various CI updates including the transition to the new Kubernetes-based zephyr-runner.
* ci: Update actions 
* ci: Convert deprecated 'set-output' command usage
* ci: Use zephyr-runner
=> Various CI updates

.github/workflows/ci.yml
This series updates the CI workflow to natively build the AArch64 Linux and AArch64 macOS toolchains using the AArch64 Linux zephyr-runner and the AArch64 macOS zephyr-runner, respectively.
It also adds the test environments for the `linux-aarch64` and `macos-aarch64` distribution bundles using the AArch64 zephyr-runners.
Note that the Intel (x86) Mac Mini zephyr-runners have been phased out and replaced by the Apple Silicon (M1) Mac Mini zephyr-runners as part of this. The `macos-x86_64` toolchains are now cross-compiled from the AArch64 macOS. The testing of the `macos-x86_64` distribution bundle is done on the AArch64 macOS using Rosetta 2 emulation.
Closes #425 
Closes #442
=> ci: Use AArch64 zephyr-runner to natively build and test AArch64 Linux and macOS toolchains

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
Related to https://github.com/zephyrproject-rtos/zephyr/pull/51932 .
If merged, Zephyr now has a QEMU/KVM AArch64 board, so the SDK supporting it would be nice.
=> qemu: Enable KVM

cmake/zephyr/Kconfig
This commit renames the `TOOLCHAIN_ZEPHYR_0_15` Kconfig symbol to `TOOLCHAIN_ZEPHYR_0_16` in preparation for the Zephyr SDK 0.16.0 release.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
=> cmake: Update Kconfig symbol name for 0.16 release

cmake/Zephyr-sdkConfigVersion.cmake
During review of https://github.com/zephyrproject-rtos/zephyr/pull/53833 it became clear that existing description regarding minimum compatible version was unclear. Also the variable name
`ZEPHYR_MINIMUM_COMPATIBLE_VERSION` could be mistaken for referring to Zephyr itself, and not the Zephyr SDK.
Improve the description to be more precise that we are referring to Zephyr SDK versions. Update `ZEPHYR_MINIMUM_COMPATIBLE_VERSION` to `ZEPHYR_SDK_MINIMUM_COMPATIBLE_VERSION`.
=> cmake: improve text description on minimum compatible versions

.github/workflows/ci.yml
This commit disables the testing of the
`xtensa-espressif_esp32s3_zephyr-elf` toolchain because the `esp32s3_devkitc` board has not been upstreamed yet.
Revert this commit when the `esp32s3_devkitc` board is upstreamed.
=> ci: Disable testing of xtensa-espressif_esp32s3_zephyr-elf toolchain

.github/workflows/ci.yml, configs/common.config
This commit introduces the common toolchain configuration file, common.config, that specifies the crosstool-ng toolchain configurations that are common to all toolchain variants.
The configurations in common.config are applied before the configurations in each toolchain configuration file.
=> configs: Add common toolchain configuration file

configs/common.config
This commit updates the common toolchain configurations to explicitly set the list of supported terminal types for the ncurses library and adds `screen`, `screen-256color`, `tmux`, `tmux-256color` terminal type support.
These terminal types are required in order to properly handle user inputs (e.g. for GDB shell) inside tmux.
---
Closes https://github.com/zephyrproject-rtos/sdk-ng/issues/633
=> configs: common: Add tmux support for ncurses

.github/workflows/ci.yml
This commit updates the CI workflow to grant write permission to the toolchain build output directory and its sub-directories before attempting to clean up unneeded files.
This is necessary because crosstool-ng may create output directories without write permission (e.g. when building on macOS).
=> ci: Grant write permission before toolchain output directory cleanup

cmake/zephyr_sdk_export.cmake
This switches to use /tmp as a temporary path on linux and mac since normal users do not generally have write permission to the system location where zephyr SDK files are located, which would otherwise prevent them from registering it.
Note: not tried this with windows/mac, worked with zephyr sdk 0.16.0 on linux
=> cmake: Use /tmp path on linux/mac

.github/workflows/ci.yml
This commit updates the CI workflow to disable testing of the `xtensa-intel_apl_adsp_zephyr-elf` toolchain because the `intel_adsp_cavs15` board was removed from the upstream Zephyr and there currently is no upstream board that uses this toolchain.
=> ci: Disable testing of xtensa-intel_apl_adsp_zephyr-elf

.github/workflows/ci.yml
This commit updates the CI workflow to disable testing of the `xtensa-intel_s1000_zephyr-elf` toolchain because the `intel_adsp_cavs18` board was removed from the upstream Zephyr and there currently is no upstream board that uses this toolchain.
=> ci: Disable testing of xtensa-intel_s1000_zephyr-elf

cmake/zephyr/Kconfig
This commit updates the Zephyr SDK Kconfig to select `HAS_NEWLIB_LIBC_NANO` unconditionally because the Newlib nano variant is now available on all targets supported by the Zephyr SDK.
=> cmake: Select HAS_NEWLIB_LIBC_NANO unconditionally

cmake/zephyr/Kconfig
This commit temporarily disables the Newlib nano variant for the Xtensa architecture because there is a bug in the nano `memset` implementation causing a system crash (see the GitHub issue #660).
Revert this commit when #660 is fixed.
=> cmake: Disable Newlib-nano for Xtensa

.github/workflows/ci.yml
This commit updates the CI workflow to use the Zephyr `topic-sdk-dev` branch, which contains the Zephyr-side patches required for the latest Zephyr SDK changes, for testing.
=> ci: Use Zephyr topic-sdk-dev branch for testing

README.md
This series adds the process for updating the submodules in the Zephyr SDK repository, along with the requirement for keeping the Zephyr SDK `picolibc` submodule and the Zephyr `picolibc` module synchronised.
Related to https://github.com/zephyrproject-rtos/zephyr/pull/58006
Part of https://github.com/zephyrproject-rtos/zephyr/issues/49922
=> README: Add submodule update process

.github/workflows/ci.yml
Some of the test platforms might not be enabled with zephyr toolchain
yet, so force toolchain to be able to test platforms with the new SDK.
=> ci: when testing with twister, force toolchain

meta-zephyr-sdk/recipes-devtools/arc_qemu/arc-qemu_git.bb
This commit updates the ARC QEMU to 2023.07.28 tag.
There are multiple fixes, one of whose is fix of buggy delay slot implementation, which was causing issues like
https://github.com/zephyrproject-rtos/zephyr/issues/54720 (and most likely https://github.com/zephyrproject-rtos/zephyr/issues/60071)
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/54720
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/60071
=> meta-zephyr-sdk: arc_qemu: Update to 2023.07.28 release

overlays/xtensa_mtk_mt8195/gdb/gdb/xtensa-config.c
One byte error in copy/paste code.  Because I'm congenitally unable to write trivial syntax correctly the first time.  But also because we have no way to execute this code except inside of a Github CI container.
=> overlays/mt8195_adsp: Fix typo

.github/workflows/ci.yml
The board used for running Xtensa with MMU has been renamed to qemu_xtensa_mmu on Zephyr main repo. So update the CI yaml file to match.
=> ci: rename board from qemu_xtensa_dc233c to qemu_xtensa_mmu

.github/workflows/ci.yml
The "topic" branches have been superseded by the "collab" branches in the upstream Zephyr repository.
This commit updates the Zephyr SDK CI to use the renamed `collab-sdk-dev` branch, complying to the new guidelines.
=> ci: Use Zephyr collab-sdk-dev branch for testing

.github/workflows/ci.yml, overlays/xtensa_nxp_imx8ulp_adsp/gdb/gdb/xtensa-config.c
Add missing header to fix imx8ulp_adsp toolchain.
Fixes: e88c208e53a6 ("xtensa: Add 8ulp_adsp toolchain")
=> xtensa: nxp_imx8ulp_adsp: Add missing include header

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
This commit pulls in the OpenOCD patch that adds STM32WBA5xx device support.
=> openocd: Pull in STM32WBA5xx device support

contrib/linux_build_toolchain.sh
* Display the default SDK directory with the `SDK_DIR` var (currently no default is shown)
* Use quoted `'EOF'` to avoid escaping `$`, `{`, and `}` in heredoc
=> contrib: linux_build_toolchain: quote EOF and correct sdk var

.github/workflows/ci.yml, .github/workflows/release.yml
Use the next generation [zephyr-runner v2](https://github.com/zephyrproject-rtos/infrastructure/issues/152) based on the [Zephyr CI Infrastructure Architecture v2](https://github.com/zephyrproject-rtos/infrastructure/issues/150).
=> ci: Use zephyr-runner v2

configs/aarch64-zephyr-elf.config, configs/common.config, configs/x86_64-zephyr-elf.config
This change allows Zephyr developers to use most or all of the C++ facilities in gcc that depend on gthread support.
Those facilities include (but are likely not limited to)
* `std::thread`
* `std::this_thread`
* `std::mutex`
* `std::recursive_mutex`
* `std::shared_mutex`
* `std::condition_variable`
* `std::binary_semaphore`
* `std::counting_semaphore`
* `std::lock_guard`
* `std::unique_lock`
* `std::scoped_lock`
* `std::shared_lock`
* `std::syncstream`
* `std::future`
* `std::async`
\* The riscv64-zephyr-elf toolchain stack unwinding support is not used in Zephyr. This should be fixed by [zephyrproject/zephyr#69912](https://github.com/zephyrproject-rtos/zephyr/pull/69912). 
Test are in review at https://github.com/zephyrproject-rtos/zephyr/pull/43729 .
The test suites can be run with …
=> improve support for c++ threading and synchronization

.github/workflows/ci.yml
Update test platform names for HWMv2 after the `collab-sdk-dev` branch fast-forward.
While at it, also update the test target toolchain list to include all currently available toolchains.
=> ci: Update test platform names for HWMv2

.github/workflows/ci.yml
This commit updates the CI toolchain test job to build and run Zephyr libc and C++ tests and samples in order to catch more C/C++ library related regressions in the SDK CI.
=> ci: Build Zephyr libc and C++ tests and samples

configs/aarch64-zephyr-elf.config, configs/common.config, configs/x86_64-zephyr-elf.config
This reverts the toolchain configs enabling C11 threads-based libstdc++ gthread support introduced in https://github.com/zephyrproject-rtos/sdk-ng/pull/735.
This is intended to be a temporary workaround for https://github.com/zephyrproject-rtos/sdk-ng/issues/751 until one of the solutions suggested in https://github.com/zephyrproject-rtos/gcc/pull/30#issuecomment-2094635990 is implemented.
GCC PR: https://github.com/zephyrproject-rtos/gcc/pull/30
=> Revert "configs: common: enable c++11 thread support via c11 threads"

.github/workflows/ci.yml
This commit updates the CI workflow such that Zephyr C++ samples and tests are only built on Linux hosts because there is a known issue causing the following link error using non-Linux toolchains:
undefined reference to `_impure_ptr'
Revert this when the GitHub issue #760 is fixed.
=> ci: Exclude C++ sample and test builds on non-Linux hosts

.github/workflows/ci.yml
This commit updates the CI workflow to trigger on pushes to the release branches (`v*-branch`), in preparation for the upcoming maintenance releases.
=> ci: Trigger on release branches

.github/workflows/ci.yml
This commit updates the CI workflow to use the sdk-build image v1.3.1, which is based on Debian 10 (Buster) and contains Python 3.8.
=> ci: Use sdk-build v1.3.1

.github/workflows/ci.yml, .gitmodules
This series updates the CI workflow to use the "cross compilation kit"
submodules, instead of directly checking out the crosskit repositories.
=> ci: Use crosskit submodules

.github/workflows/ci.yml
This removes the the `-M` (runtime artifact cleanup) parameter from twister invocation because it causes instability when running on Windows and the artifacts for the passing tests are already cleaned up without it.
=> ci: Do not remove artifacts when running twister

cmake/zephyr/host-tools.cmake
On Windows platform, the OPENOCD_DEFAULT_PATH is not set in line with Zephyr documentation. Fixes zephyrproject-rtos/zephyr#79051.
=> Set correct OPENOCD_DEFAULT_PATH for Windows

.github/workflows/ci.yml
This commit increases the subset count for running Zephyr tests to 3 because tests are taking up to 3 hours to complete with the subset count of 2.
=> ci: Increase test subset count to 3

.github/workflows/ci.yml
This commit updates the CI workflow in the SDK 0.16 LTS branch to run tests against the Zephyr v3.7 LTS3 branch.
=> [v0.16-branch] ci: Run tests against Zephyr v3.7 branch

.github/workflows/ci.yml
This commit disables the testing of xtensa-intel_ace30_ptl_zephyr-elf toolchain because the Zephyr v3.7-branch currently does not support it.
=> [v0.16-branch] ci: Disable testing of xtensa-intel_ace30_ptl_zephyr-elf toolchain

.github/workflows/ci.yml
This commit increases the CI workflow toolchain build job timeout to 12 hours because the default value of 6 hours is insufficient for the toolchains with many multi-lib variants (e.g. ARM And RISC-V).
=> ci: Increase toolchain build timeout to 12 hours

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
Pulls in QEMU with semihosting module updated from v7.0.0 to v7.2.0. This fixes issue with semihosting that wasn't waiting for completion of one operation before starting another. https://github.com/zephyrproject-rtos/zephyr/issues/79359
=> meta-zephyr-sdk: qemu: Pull in QEMU with semihosting fix

scripts/llvm/CMakeLists.txt
Add initial RISC-V support with the most basic multi-lib variant for each base ISA to Zephyr SDK LLVM toolchain
=> [topic-clang] Add initial RISC-V support

cmake/zephyr/llvm/target.cmake, scripts/llvm/CMakeLists.txt, scripts/llvm/cmake/multilib.yaml.in, scripts/llvm/test-support/picolibc-test-wrapper.py, scripts/llvm/test/multilib/rv32e.test, scripts/llvm/test/multilib/rv32i.test, scripts/llvm/test/multilib/rv64i.test
Add RV32I, RV32E and RV64I "common" multi-libs, based on [the list of Zephyr GCC RISC-V multi-libs](https://github.com/zephyrproject-rtos/gcc/blob/e8b0df3247f3b915f50f2233c8170009e33cde84/gcc/config/riscv/t-zephyr#L64-L87).
=> [topic-clang] Add LLVM RISC-V multi-libs

.github/workflows/ci.yml
Add RISC-V platforms for LLVM testing, and disable them for now until they are fixed on the Zephyr side.
=> ci: Add RISC-V platforms for LLVM testing

overlays/xtensa_mtk_mt818x_adsp/gdb/gdb/xtensa-config.c, overlays/xtensa_mtk_mt8195_adsp/gdb/gdb/xtensa-config.c, overlays/xtensa_mtk_mt8196_adsp/gdb/gdb/xtensa-config.c
This reverts commit fff09281116059d051de84bc0afcd9500bbbfa47.
This change is cause build issues on Darwin and is not needed and not
compatible with current crosstools-ng.
Will be re-added once we have a more up to date ctng.
=> Revert "overlays/mtk: Fix linker API"

meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_9.2.1.bb
Those are needed for testing ipc/ipm in zephyr.
=> qemu: install ivshmem-server/ivshmem-client

.github/workflows/ci.yml
Target is called intel_adsp/ace30/ptl now.
=> ci: rename intel_adsp/ace30_ptl

.github/workflows/ci.yml
Use qemu_xtensa/dc233c when testing.
=> ci: fix qemu_xtensa name

meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_9.2.1.bb, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/qemu-xilinx_git.bb
Enable user-space TCP/IP stack for network emulation to be able to connect emulated ethernet controllers with host PC for testing purpose.
=> meta-zephyr-sdk: xilinx_qemu: Enable slirp

.github/workflows/ci.yml
=> ci: rename esp32_devkitc_wroom/esp32/procpu -> esp32_devkitc/esp32/procpu

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
Now use our own git2cl. The upstream repo very often is unreachable and
causes CI to fail.
=> openocd: use hosted git2cl

meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0001-Revert-target-arm-Enforce-alignment-for-LDM-STM.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0001-Revert-target-arm-Revert-back-to-YIELD-for-WFI.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0002-Enable-WFI-CPU-halting-in-icount-mode.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0003-riscvXX-softmmu-Enable-emaclite-driver-for-MB-V.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0004-riscv-Wire-CPU-timers.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/cross.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/fixedmeson.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/no-pip.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/qemu-xilinx_git.bb
@nashif reported me 3 issues which are reported by CI. 
Two of them are related to patches which have been removed but they were the part of previous QEMU version. 
Both of them are visible by running
west twister -v -p qemu_cortex_r5 -O /tmp/twister -T tests/kernel/context/
https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/15058691212/job/42329628698
https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/15058691212/job/42329629012
The last one is reproducible by running
west twister -v -p qemu_cortex_r5 -O /tmp/twister -T tests/misc/llext-edk/
https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/15058691212/job/42329629235
And it is tricky because it is coming from upstream QEMU commit  which is likely correct but still would be better to revert …
=> xilinx_qemu: CI fixes

.github/workflows/ci.yml, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0001-Revert-target-arm-Enforce-alignment-for-LDM-STM.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0001-Revert-target-arm-Revert-back-to-YIELD-for-WFI.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0002-Enable-WFI-CPU-halting-in-icount-mode.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0003-riscvXX-softmmu-Enable-emaclite-driver-for-MB-V.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/0004-riscv-Wire-CPU-timers.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/cross.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/fixedmeson.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/files/no-pip.patch, meta-zephyr-sdk/recipes-devtools/qemu_xilinx/qemu-xilinx_git.bb, meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
- **meta-zephyr-sdk: xilinx_qemu: Clean skip-meson option**
- **meta-zephyr-sdk: xilinx_qemu: Update to 8.2.7 QEMU**
- **meta-zephyr-sdk: xilinx_qemu: Fix qemu WFI behavior**
- **meta-zephyr-sdk: xilinx_qemu: Enable CPU timers and emaclite for MB-V**
- **meta-zephyr-sdk: xilinx_qemu: Disable alignment for R5**
=> [backport 0.17-branch] xilinx qemu fixes + ci optimizations

.github/workflows/ci.yml, cmake/Zephyr-sdkConfig.cmake, cmake/zephyr/Kconfig, meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_10.0.2.bb
Use alternative variant handling keeping zephyr variant supported.
=> cmake: bump version of SDK in Kconfig / use new variant syntax

.github/workflows/ci.yml, release-notes.md
- **doc: update release notes**
- **tests: add --no-detailed-test-id to twister call**
- **ci: twister: retry build errors**
=> misc ci tweaks

.github/workflows/ci.yml
Zephyr now requires python 3.12, so install this version when testing
the SDK.
=> [0.17-branch] ci: when testing, install python 3.12, required by zephyr now

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-target-xtensa-add-translation-for-wsr.mpucfg.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0002-target-xtensa-import-sample_controller32-core.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0003-tests-tcg-xtensa-tidy-test-linker-script.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0004-tests-tcg-xtensa-fix-SR-test-for-configs-with-MPU.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0005-target-xtensa-fix-sample_controller32-build-for-QEMU.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0006-Revert-target-xtensa-Make-use-of-segment-in-pptlb-he.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0007-qemu-Add-addition-environment-space-to-boot-loader-q.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0008-apic-fixup-fallthrough-to-PIC.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0009-qemu-Do-not-include-file-if-not-exists.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0010-qemu-Add-some-user-space-mmap-tweaks-to-address-musl.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0011-qemu-Determinism-fixes.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0012-tests-meson.build-use-relative-path-to-refer-to-file.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0013-Define-MAP_SYNC-and-MAP_SHARED_VALIDATE-on-needed-li.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0014-configure-lookup-meson-exutable-from-PATH.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0015-qemu-Ensure-pip-and-the-python-venv-aren-t-used-for-.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0016-target-riscv-kvm-do-not-use-non-portable-strerrornam.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0017-hw-timer-renesas_cmt-Update-renesas_cmt-timer.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0018-target-rx-Update-flow-of-interrupt-execution-for-tar.patch, meta-zephyr-sdk/recipes-devtools/qemu/files/0019-target-rx-Reset-the-CPU-at-qemu-reset-time.patch, meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_10.0.2.bb
This commit adding 2 patch to fix for qemu_rx
1st patch is to fix for timer accurarcy issue
2nd patch is to fix for flow of execute interrupt handling function for normal interrup and CPU exception
Same patch as https://github.com/zephyrproject-rtos/sdk-ng/pull/944 but v0.17 based
=> [v0.17-branch] qemu: Adding patch to fix qemu rx

.github/workflows/ci.yml
This commit updates the CI workflow to use the SDK build image v1.3.9, which updates the Debian Buster APT repository URL to `archive.debian.org` because `deb.debian.org` no longer hosts the Debian Buster packages.
=> ci: Use sdk-build v1.3.9

meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_git.bb
This commit pulls in various RX architecture fixes for QEMU from zephyrproject-rtos/sdk-ng#944.
From the original PR:
> * 1st patch is to fix for timer accurarcy issue
> * 2nd patch is to fix for flow of execute interrupt handling function for
normal interrup and CPU exception
> * 3rd patch is to add Reset the CPU at qemu reset time so elf target can
be execute when use device loader
---
QEMU PR: https://github.com/zephyrproject-rtos/qemu/pull/11
=> meta-zephyr-sdk: qemu: Pull in RX arch fixes

.github/workflows/ci.yml
This commit updates the CI workflow to use the SDK build image v1.3.9, which updates the Debian Buster APT repository URL to `archive.debian.org` because `deb.debian.org` no longer hosts the Debian Buster packages.
Note that the MinGW-related additions in the sdk-build v1.3.9 image does not affect the SDK 0.17 build because the CI workflow does not actively attempt to use them.
=> [v0.17-branch] ci: Use sdk-build v1.3.9

meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_git.bb
The original change making QEMU use Zephyr SeaBIOS fork, 1bf6f4affb772d50c19af6c1a5a8e555eb4a2be3, was dropped by mistake during the upgrade to QEMU 10.0.2.
This commit updates the QEMU recipe to use the pre-built x86 BIOS binaries from the Zephyr SeaBIOS fork.
The Zephyr SeaBIOS fork contains a few additional patches to make debugging more convenient for x86 QEMU targets (e.g. not clearing screen on reset).
---
Fixes https://github.com/zephyrproject-rtos/sdk-ng/issues/967
To be backported to `v0.17-branch`.
=> meta-zephyr-sdk: qemu: Use Zephyr SeaBIOS fork binaries

.github/workflows/ci.yml
This commit pulls in the GDB patch that sets `_WIN32_WINNT` to 0x0600
when not explicitly defined in the CFLAGS.
Note that, libstdc++, when building with the win32 thread model, only
supports std::mutex and std:condition_variable if _WIN32_WINNT >=
0x0600.
---
GDB PR: https://github.com/zephyrproject-rtos/binutils-gdb/pull/18
Tested in https://github.com/zephyrproject-rtos/sdk-ng/actions/runs/16438257464
Fixes https://github.com/zephyrproject-rtos/sdk-ng/issues/964
=> gdb: Default to _WIN32_WINNT=0x0600

.github/workflows/ci.yml
The Linux CI Docker image is now based on Ubuntu 24.04, and the macOS zephyr-runner runs with macOS 15.3-based image.
=> ci: Fix Linux and macOS test names

cmake/zephyr/Kconfig
The previously detected regressions when building with -Os on RISC-V have been resolved.
=> cmake: Allow -Os on RISC-V again

.github/workflows/ci.yml
gh (GitHub CLI) is required for downloading artifacts in the test job.
=> ci: Install gh for test job

meta-zephyr-sdk/recipes-devtools/qemu_arc/qemu-arc_git.bb
Move to current synopsys master version:
Implement {push,pop}dl_s.
Rewrite translation functions for memory operations
Add FPUv2 instructions.
=> qemu-arc: Fix arc64 emulation bugs for double load/store operations

cmake/zephyr/llvm/target.cmake
This PR replaces the space with an equal sign when assigning the clang configuration file to the --config parameter.
This change improves compatibility with tools, such as CodeChecker, that parse the compilation database and expect compiler arguments to be separated by space.
This PR is essentially a port of https://github.com/zephyrproject-rtos/zephyr/pull/91841.
=> cmake: llvm: Use '=' for --config to improve compatibility

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
Adds support for pix64gx curiosity, pic64gx, polarfire soc and embedded flashpro5
---
OpenOCD PR: https://github.com/zephyrproject-rtos/openocd/pull/71
=> add cfg: microchip board, targets and interface
