.shippable.yml
build.sh

ci: build using script in matrix

---

.gitignore
.shippable.yml
configs/arc.config
configs/arm.config
configs/i586.config
configs/iamcu.config
configs/nios2.config
configs/riscv32.config
go.sh
patches/0001-iamcu-support-x86-iamcu-ABIs.patch

- Add ARC (Fixes #7)
- Build IAMCU correctly
- Use latest version of xtools

Various updates and fixes

---

.shippable.yml

ci: upload built toolchain to cloud

---

configs/riscv32.config

Do not build multilib for riscv32.

riscv32: do not built multilib

---

scripts/make_zephyr_sdk.sh

Need to explicit pass flags to tar as older versions don't auto handle
the compression.
Fixes: #61

Fix tar expansion with older version of tar

---

patches/binutils/2.32/0001-GAS-Arm-PR24559-Fix-pseudo-load-operations-for-Armv8.patch

Address #75, making this draft for now til the fix gets committed upstream.

Cortex m23 asm fix

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

Update openocd to pull in an openocd GDB server fix from the ARC guys
Fixes #65

openocd: Update for gdb server fix

---

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-qemu-nios2-Add-Altera-MAX-10-board-support-for-Zephy.patch
meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

qemu: bump to 4.1.0-rc4 release

---

patches/binutils/2.32/0012-RISC-V-Fix-lui-relaxation-issue-with-code-at-address.patch

Fix for issue https://github.com/zephyrproject-rtos/zephyr/issues/18198

Fix for link error on RISC-V

---

go.sh

Update crosstool-ng version

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

openocd: update SHA to pull in ARC updates

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

openocd: update SHA to pull in build fix

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

openocd: bump sha for zephyr rtos awareness fix

---

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-qemu-nios2-Add-Altera-MAX-10-board-support-for-Zephy.patch
meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

qemu: bump to v4.2.0-rc0

---

.shippable.yml

ci: try building sdk with ci container 0.9.4

---

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

qemu: bump to v4.2.0-rc4

---

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

qemu: bump to v4.2.0-rc5

---

.shippable.yml

ci: bump to 0.10.0 of ci image

---

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

qemu: Bump to v4.2.0

---

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-hw-sparc-Add-leon-at697-machine.patch
meta-zephyr-sdk/recipes-devtools/qemu/files/0002-hw-sparc-leon-Fix-compilation-errors.patch
meta-zephyr-sdk/recipes-devtools/qemu/files/0003-hw-sparc-leon-timer-Call-leon_timer_io_read-for-TIME.patch
meta-zephyr-sdk/recipes-devtools/qemu/files/0004-hw-sparc-leon-Switch-to-transaction-based-ptimer-API.patch
meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

Hi,
This is a patch to add LEON2 to SPARC architecture.   This is need to run SPARC arch PR for Zephyr.  This is one commit having 3 patches.  Each patch is in Git format style and has its own commit log.
This PR is more of a request for comment because I've never added patch to sdk-ng.   Feedback comment will be appreciated.

qemu: Add leon2 support

---

release-notes.md

Add a file to track changes and note about any requirements or issues
that one might run into.

release-notes.md: Add a release note file

---

scripts/make_zephyr_sdk.sh

make_zephyr_sdk: update for new xtensa variants

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

openocd: Bump SHA for ARC SMP fix

---

README.md

Provide some clues to people who might want to try out SDK
customizations.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>

README: update with helpful developer information

---

.buildkite/deploy.yml

* support for publishing releases (based on tag) to GitHub
* support for publishing PRs to S3

ci: deploy.yml: Add support to publish builds

---

.buildkite/pipeline.yml

ci: buildkite: use sdk-ng-deploy pipeline

---

meta-zephyr-sdk/recipes-hosttools/bossa/bossa_git.bb
meta-zephyr-sdk/recipes-hosttools/bossa/files/0001-Wait-for-EEFC-flash-to-complete-operations-before-re.patch

Pull in bossa updates posted 1.9.1 plus a patch fix to get Arduino Due
flashing working.
(Fix PR from https://github.com/shumatech/BOSSA/pull/111/commits).

Update bossa to 1.9.1+

---

.buildkite/deploy.yml

ci: deploy: Update for handling aarch and x86_64 builds

---

go.sh

crosstool-ng: Update to newer version with picolibc updates

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

openocd: Update to recent upstream (20200928)

---

meta-zephyr-sdk/recipes-hosttools/bossa/bossa_git.bb
meta-zephyr-sdk/recipes-hosttools/bossa/files/0001-Flash.h-Add-flash-override-samba-error.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0002-CalwFlash-Add-SAM4L-Flashcalw-controller.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0003-Device-Introduce-support-to-SAM4L-SoC-family.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0004-CalwFlash-Add-NVIC-reset-command.patch
release-notes.md

Pull in changes from https://github.com/shumatech/BOSSA/pull/143

bossa: Pull in Add support to SAM4L SoC Family

---

meta-zephyr-sdk/recipes-devtools/qemu/files/0010-target-riscv-Fix-the-translation-of-physical-address.patch
meta-zephyr-sdk/recipes-devtools/qemu/files/0011-target-riscv-Change-the-TLB-page-size-depends-on-PMP.patch
meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
release-notes.md

Pull in some fixes related to PMP support on RISCV from upstream qemu
Fixes #277

qemu: backport some pmp riscv fixes from upstream

---

go.sh

Increase the macOS sparse disk image size

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb

openocd: Update to recent upstream (20201109)

---

go.sh

Upstream merged some of our changes, resync with it.

crosstool-ng: resync w/upstream

---

meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

qemu: Update to qemu 6 release

---

meta-zephyr-sdk/recipes-hosttools/openocd/openocd_0.10.0.bb
release-notes.md

openocd: Update to recent upstream (20210630)

---

go.sh

crosstool-ng: pull in fix to strip nano libs

---

meta-zephyr-sdk/recipes-devtools/qemu/files/0017-target-arm-Use-correct-SP-in-M-profile-exception-ret.patch
meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb

Pull in a patch from upstream qemu to fix issue with TFM

qemu: Backport fix for TFM

---

release-notes.md

VERSION: Bump version to 0.13.0-rc2

---

go.sh

Cleanup script and rework things to be more explicit

go.sh: Rework build script

---

.buildkite/deploy.yml

Update deploy.yml to handle artifact filenames include the OS

ci: tweak deploy script for filenames

---

.buildkite/pipeline-template.yml
go.sh
scripts/make_zephyr_sdk.sh

To prep for support different build variants for MacOS & Linux add OS
into filenames and such to handle different builds.

ci: Update pipeline.yml for handling OS

---

go.sh

Add a target that just creates and mounts the MacOS disk image.
Additionally, move macos specific setup for crosstool-ng into
build_crosstool() function.

go.sh: add macos_setup_diskimage target

---

.buildkite/deploy.yml
scripts/make_zephyr_sdk.sh

ci: Update make_zephyr_sdk and deploy to take OS and MACHINE

---

README.md

Replaces outdated information with more up-to-date/generic, fixing
typos and formatting issues on the way.
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

README: Update to current state of affairs.

---

scripts/template_setup_posix

This commit updates the POSIX setup script to validate the user inputs
in the interactive mode.

scripts: template_setup_posix: Add interactive mode user input check

---

.github/workflows/ci.yml
scripts/template_setup_posix
scripts/template_setup_win

This series adds the changes to support building the "minimal distribution bundle."
Closes #450

Add minimal distribution bundle

---

.github/workflows/ci.yml

Install ninja and meson, which are required for building the picolibc.

ci: Install ninja and meson

---

.github/workflows/ci.yml

ci: enable esp32s3_devkitm testing

---

README.md

This commit updates the list of supported architectures in the README to include the recently added architectures.

README: Update supported architecture list

---

README.md
contrib/linux_build_toolchain.sh

A very primitive script to build one toolchain locally on Linux.
... hopefully easing some pains on developers when introducing a new toolchain.

contrib: bash script to build one toolchain locally on Linux

---

overlays/xtensa_mtk_mt818x_adsp/gdb/gdb/xtensa-config.c
overlays/xtensa_mtk_mt8195_adsp/gdb/gdb/xtensa-config.c
overlays/xtensa_mtk_mt8196_adsp/gdb/gdb/xtensa-config.c
overlays/xtensa_mtk_mt8365_adsp/gdb/gdb/xtensa-config.c

- **Reapply "overlays/mtk: Fix linker API"**
- **overlays/mtk: remove alias**

reapply reverted change and fix in a new commit

---

.github/workflows/ci.yml

ci: rename mps3/an547 to mps3/corstone300/an547

---

.github/workflows/ci.yml

This reverts commit e7ba84516badea2c2885aa447b1db5732a40073c.

Revert "ci: disable testing on qemu_rx, still wip"

---

meta-zephyr-sdk/recipes-devtools/qemu/files/0001-Revert-target-xtensa-Make-use-of-segment-in-pptlb-he.patch
meta-zephyr-sdk/recipes-devtools/qemu/qemu-zephyr_9.2.3.bb

Revert upstream commit breaking mpu.

hosttools: fix qemu_xtensa sample_controller32

---

.github/workflows/ci.yml

Fix test names for Linux, macOS and Windows in the CI workflow

[v0.17-branch] ci: Fix test names

---

scripts/template_setup_win

This PR fixes #1022.
(@tdewey-rpi @will-v-pi)

Fix #1022, Typo in LLVM toolchain install path - setup.cmd
